Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
orbit_plot = rd.interactive_orbit_campbell_async(
    campbell_fig,
    A1_async,
    A1_async,
    1,
    0.5,
    initial_speed=2700,
    max_amplitude=2e-05
)
orbit_plot.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 1[0m
[0;32m----> 1[0m orbit_plot [38;5;241m=[39m [43mrd[49m[38;5;241;43m.[39;49m[43minteractive_orbit_campbell_async[49m[43m([49m
[1;32m      2[0m [43m    [49m[43mcampbell_fig[49m[43m,[49m
[1;32m      3[0m [43m    [49m[43mA1_async[49m[43m,[49m
[1;32m      4[0m [43m    [49m[43mA1_async[49m[43m,[49m
[1;32m      5[0m [43m    [49m[38;5;241;43m1[39;49m[43m,[49m
[1;32m      6[0m [43m    [49m[38;5;241;43m0.5[39;49m[43m,[49m
[1;32m      7[0m [43m    [49m[43minitial_speed[49m[38;5;241;43m=[39;49m[38;5;241;43m2700[39;49m[43m,[49m
[1;32m      8[0m [43m    [49m[43mmax_amplitude[49m[38;5;241;43m=[39;49m[38;5;241;43m2e-05[39;49m
[1;32m      9[0m [43m)[49m
[1;32m     10[0m orbit_plot[38;5;241m.[39mshow()

[0;31mTypeError[0m: interactive_orbit_campbell_async() got an unexpected keyword argument 'max_amplitude'

